sequenceDiagram
    participant user
    participant browser
    participant server

    user ->> browser: Opens URL on the browser
    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server-->>browser: HTML document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: the css file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: the JavaScript file
    deactivate server

    Note right of browser: The browser starts executing the JavaScript code that fetches the JSON from the server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: [{"content": "8======================================3","date": "2025-09-16T21:31:08.760Z"}, ... ]
    deactivate server

    Note right of browser: The browser executes the callback function that renders the notes

    %% User creates a new note
    user ->> browser: Types note and clicks "Save"
    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    activate server
    server-->>browser: HTML document application/x-www-form-urlencoded
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/new
    activate server
    server-->>browser: HTML document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: the css file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: the JavaScript file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: [...,{"content": "lachi.dong","date": "2025-09-17T06:33:25.428Z"}]
    deactivate server

 Note right of browser: The browser starts executing the JavaScript code that fetches the JSON from the server